/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HTC' at '07.07.2017 16:21' with Gradle 2.9
 *
 * @author HTC, @date 07.07.2017 16:21
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
